---
name: PerlCritic

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Check with PerlCritic
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Install PerlCritic
        run: |
          sudo apt update -y
          sudo apt install libperl-critic-perl
      - name: Run PerlCritic
        run: perlcritic *kml*
