---
name: PerlCritic

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Check with PerlCritic
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Install PerlCritic
      run: |
        sudo apt update -y
        sudo apt install libperl-critic-perl
    - name: Run PerlCritic
      run: perlcritic *kml*
