---
name: PerlCritic

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Check with PerlCritic
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install PerlCritic
        run: |
          sudo apt update -y
          sudo apt install libperl-critic-perl
      - name: Run PerlCritic
        run: perlcritic *kml*
