name: PerlCritic

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    # run only on internal PRs, external ones already run on push.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install PerlCritic
      run: |
        sudo apt update -y
        sudo apt install libperl-critic-perl
    - name: Run PerlCritic
      run: perlcritic *kml*
